### ISSUE TITLE
plot_benchmarks memory column is non-numeric

### ISSUE THREAD

**Issue by sajanraju** [SchlossLab/mikropml-snakemake-workflow#11]
Hi,

I am facing the below error for the plot_benchmarks. Any idea how to correct it?
I am using a macbook pro to run the mikropml locally with data  (800+ genus column, 160 samples and a metadata variable with healthy and case group). 

```
Error in rule plot_benchmarks:
    jobid: 41
    output: figures/benchmarks.png
    log: log/plot_benchmarks.txt (check log file(s) for error message)
```

```
────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Error: Problem with `mutate()` column `memory_gb`.
ℹ `memory_gb = max_rss/1024`.
✖ non-numeric argument to binary operator
Backtrace:
     █
  1. ├─`%>%`(...)
  2. ├─dplyr::group_by(., method)
  3. ├─tidyr::pivot_longer(., -method, names_to = "metric")
  4. ├─dplyr::select(., method, runtime_mins, memory_gb)
  5. ├─dplyr::mutate(., runtime_mins = s/60, memory_gb = max_rss/1024)
  6. ├─dplyr:::mutate.data.frame(., runtime_mins = s/60, memory_gb = max_rss/1024)
  7. │ └─dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
  8. │   ├─base::withCallingHandlers(...)
  9. │   └─mask$eval_all_mutate(quo)
 10. └─base::.handleSimpleError(...)
 11.   └─dplyr:::h(simpleError(msg, call))
Execution halted
```

**Comment by kelly-sovacool** [comment]
Hi @sajanraju, I transferred this issue from the mikropml repo to the mikropml-snakemake-workflow repo, since this is a problem with running the snakemake workflow, not with the package.

In the rule `run_ml` we use the `benchmark` directive, which tells snakemake to record the runtime, memory usage, etc for those jobs. `max_rss` is a column that corresponds to the memory usage in kilobytes, which should normally be a numeric value. The rule `combine_benchmarks` concatenates all of the benchmark files together, and `plot_benchmarks` then takes this combined benchmark file and plots it using [this script](https://github.com/SchlossLab/mikropml-snakemake-workflow/blob/main/code/plot_benchmarks.R). 

The important part of that error message is:
```
Error: Problem with `mutate()` column `memory_gb`.
ℹ `memory_gb = max_rss/1024`.
✖ non-numeric argument to binary operator
```

That tells us that when `read_csv` created the dataframe, it decided to make the `max_rss` column non-numeric. Instead of letting `read_csv` guess the data types of the columns in the csv file, we can explicitly tell it to use certain ones with the [`col_types` option](https://readr.tidyverse.org/reference/read_delim.html) like this:

```R
dat <- read_csv(snakemake@input[['csv']],
                col_types = cols(
                  s = col_double(),
                  `h:m:s` = col_time(format = "%H:%M:%S"),
                  max_rss = col_double(),
                  max_vms = col_double(),
                  max_uss = col_double(),
                  max_pss = col_double(),
                  io_in = col_double(),
                  io_out = col_double(),
                  mean_load = col_double(),
                  cpu_time = col_double(),
                  method = col_character(),
                  seed = col_double()
                )) %>%
...
```

Let me know if this fixes your error.
If not, there may be a stray character or something in one of your benchmark files.

**Comment by sajanraju** [comment]
Hey Kelly, 

`Thanks a lot. it worked !!! `

 👍
